/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnairaRouteImport } from './routes/_authenticated.anaira'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated.calendar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated.insights'
import { Route as AuthenticatedMockJuryRouteImport } from './routes/_authenticated.mock-jury'
import { Route as AuthenticatedPageantsRouteImport } from './routes/_authenticated.pageants'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated.plan'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedProvidersRouteImport } from './routes/_authenticated.providers'
import { Route as AuthenticatedSkinAnalysisRouteImport } from './routes/_authenticated.skin-analysis'
import { Route as AuthenticatedTrackerRouteImport } from './routes/_authenticated.tracker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnairaRoute = AuthenticatedAnairaRouteImport.update({
  id: '/anaira',
  path: '/anaira',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMockJuryRoute = AuthenticatedMockJuryRouteImport.update({
  id: '/mock-jury',
  path: '/mock-jury',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPageantsRoute = AuthenticatedPageantsRouteImport.update({
  id: '/pageants',
  path: '/pageants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProvidersRoute = AuthenticatedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSkinAnalysisRoute =
  AuthenticatedSkinAnalysisRouteImport.update({
    id: '/skin-analysis',
    path: '/skin-analysis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrackerRoute = AuthenticatedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/anaira': typeof AuthenticatedAnairaRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/mock-jury': typeof AuthenticatedMockJuryRoute
  '/pageants': typeof AuthenticatedPageantsRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/skin-analysis': typeof AuthenticatedSkinAnalysisRoute
  '/tracker': typeof AuthenticatedTrackerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/anaira': typeof AuthenticatedAnairaRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/mock-jury': typeof AuthenticatedMockJuryRoute
  '/pageants': typeof AuthenticatedPageantsRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/skin-analysis': typeof AuthenticatedSkinAnalysisRoute
  '/tracker': typeof AuthenticatedTrackerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/anaira': typeof AuthenticatedAnairaRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/mock-jury': typeof AuthenticatedMockJuryRoute
  '/_authenticated/pageants': typeof AuthenticatedPageantsRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/providers': typeof AuthenticatedProvidersRoute
  '/_authenticated/skin-analysis': typeof AuthenticatedSkinAnalysisRoute
  '/_authenticated/tracker': typeof AuthenticatedTrackerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/anaira'
    | '/calendar'
    | '/dashboard'
    | '/insights'
    | '/mock-jury'
    | '/pageants'
    | '/plan'
    | '/profile'
    | '/providers'
    | '/skin-analysis'
    | '/tracker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/anaira'
    | '/calendar'
    | '/dashboard'
    | '/insights'
    | '/mock-jury'
    | '/pageants'
    | '/plan'
    | '/profile'
    | '/providers'
    | '/skin-analysis'
    | '/tracker'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/anaira'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/insights'
    | '/_authenticated/mock-jury'
    | '/_authenticated/pageants'
    | '/_authenticated/plan'
    | '/_authenticated/profile'
    | '/_authenticated/providers'
    | '/_authenticated/skin-analysis'
    | '/_authenticated/tracker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/anaira': {
      id: '/_authenticated/anaira'
      path: '/anaira'
      fullPath: '/anaira'
      preLoaderRoute: typeof AuthenticatedAnairaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock-jury': {
      id: '/_authenticated/mock-jury'
      path: '/mock-jury'
      fullPath: '/mock-jury'
      preLoaderRoute: typeof AuthenticatedMockJuryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pageants': {
      id: '/_authenticated/pageants'
      path: '/pageants'
      fullPath: '/pageants'
      preLoaderRoute: typeof AuthenticatedPageantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/providers': {
      id: '/_authenticated/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/skin-analysis': {
      id: '/_authenticated/skin-analysis'
      path: '/skin-analysis'
      fullPath: '/skin-analysis'
      preLoaderRoute: typeof AuthenticatedSkinAnalysisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracker': {
      id: '/_authenticated/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnairaRoute: typeof AuthenticatedAnairaRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedMockJuryRoute: typeof AuthenticatedMockJuryRoute
  AuthenticatedPageantsRoute: typeof AuthenticatedPageantsRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProvidersRoute: typeof AuthenticatedProvidersRoute
  AuthenticatedSkinAnalysisRoute: typeof AuthenticatedSkinAnalysisRoute
  AuthenticatedTrackerRoute: typeof AuthenticatedTrackerRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnairaRoute: AuthenticatedAnairaRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedMockJuryRoute: AuthenticatedMockJuryRoute,
  AuthenticatedPageantsRoute: AuthenticatedPageantsRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProvidersRoute: AuthenticatedProvidersRoute,
  AuthenticatedSkinAnalysisRoute: AuthenticatedSkinAnalysisRoute,
  AuthenticatedTrackerRoute: AuthenticatedTrackerRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
